### ISSUE TITLE
💡 Proposal - simplified approach to form elements and forms in v4

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#1154]
## The problem

Our current API for form elements is a bit confusing. Historically, we provided quite granular API to allow our customers to build their own custom solutions. For example, we provide Checkbox and CheckboxField, where Checkbox (under the hood ControlledInput) is a "naked" input, without label and CheckboxField is the one providing FormLabel, ValidationMessage and HelpText. 
Right now we have:

`Checkbox`
`CheckboxField`
`ControlledInput`
`ControlledInputField`
`Form`
`FormLabel`
`RadioButton`
`RadioButtonField`
`Select`
`SelectField`
`Textarea`
`TextField`
`TextInput`
`Switch`

## The proposed solution

I propose that we merge our components and this way we provide a bit simpler approach to form elements.

We could have 2 groups of components:

### Form layouts
Form - to hold the form, set the layout for it (where buttons should be placed maybe?) and control the submit

```
<Form label="This could be a label for a group" onSubmit={}>
  <TextInput label="User name" prefix={<AvatarIcon />} type="text" placholder="Type your name here" />
  <TextInput label="Password" prefix={<AvatarIcon />} type="password" placholder="Type your name" />
  <Button>Submit<Button>
</Form>
```

FormElementsGroup - to wrap and control form elements like Checkboxes, radio buttons"
```
<FormElementsGroup label="This could be a label for a group" as="div">
  <Checkbox label="checkbox-1" />
  <Checkbox label="checkbox-2" />
  <Checkbox label="checkbox-3" />
</FormElementsGroup>
```

### Form elements
They could all contain an option to have a label as a prop, same for help text and validation message. This way we could merge 2 components into one for each case. We would end up with:

`Checkbox`
`RadioButton`
`Select`
`Textarea`
`TextInput`
`Switch`

ControlledInput / BaseInput

**props:**
`label` -  optional prop. I think we could consider labels as something that is required for form elements, but we will have some cases where Select or Textarea is used in another context than form. In that case, we would enforce aria-label?
`name`
`value`
`id`
`testId`
`isDisabled`
`isInvalid`- responsible for displaying validationMessage
`withHelpText`
`withLink` - with a link above the input on the right side
`onChange`
`isRequired` - is adding (required) to the label
`isIndeterminate` - only for Checkbox
`isChecked`
`type`
`prefix` - for TextInput to display an icon at the before the input
`sufix` - for TextInput to display icon at the end of the input or maybe even a Button (like in the case where we would like to display a copy button)

### Overview of couple of examples of new form elements:

 <img width="837" alt="Screenshot 2021-08-04 at 21 18 33" src="https://user-images.githubusercontent.com/4272331/128241735-b95e212a-b3b1-4a3b-8531-6ba10fd15601.png">
 
<img width="778" alt="Screenshot 2021-08-04 at 21 19 54" src="https://user-images.githubusercontent.com/4272331/128241902-886f7468-3e89-45d9-9186-62739f16a33d.png">

<img width="672" alt="Screenshot 2021-08-04 at 21 20 26" src="https://user-images.githubusercontent.com/4272331/128241954-44fff1dc-74e2-41f4-a813-bced91f2fb6f.png">

## Breaking changes
v4

## Open questions
 - do we want to have a SearchInput as part of this proposal (btw, is it really correct if the search is not wrapped into form? This is how we do it now, but I am not 100% sure if that's the correct and a11y way of doing it)
  - do we need to provide an option for components to appear without labels, like Checkbox for example? If label would be optional, we should enforce aria-label in that case?
 - in order to provide great experience building forms and using our API we need to provide documentation for components, but also guidelines regarding how to build forms and our design recommendations. @domarku @fabe @damann your insights here would be a great help.

**Comment by suevalov** [comment]
I think the proposal makes sense but we need to make sure that the new API will work nicely with common form libraries: 

https://formik.org/docs/overview
https://react-hook-form.com/get-started/

**Comment by gui-santos** [comment]
Great stuff! I think this will improve the Forms experience a lot 🙌 
The FormElementsGroup is a great proposal and with the `as` prop with will be very easy to build stuff

I have a few comments about some of the proposed things and also my opinions on the "Open questions", but I really like this approach to the Form Elements, thanks for taking the time to come up with this plan 🍰 

> withLink - with a link above the input on the right side

I didn't understand the reason behind this, but maybe it will be clearer once this is implemented

> prefix - for TextInput to display an icon at the before the input
> sufix - for TextInput to display icon at the end of the input or maybe even a Button (like in the case where we would like to display a copy button)

What if we do something more explicit for those cases? Maybe an `icon` prop where you pass an icon and a `iconPosition` prop with two options ("start" and "end")
I, personally, think `prefix` and `sufix` are harder to understand

Also, +100 to @suevalov comment. Especially around the onSubmit, validation messages and help text you mentioned

## My two cents to the open questions

> do we want to have a SearchInput as part of this proposal (btw, is it really correct if the search is not wrapped into form? This is how we do it now, but I am not 100% sure if that's the correct and a11y way of doing it)

Yep, it's fine to not wrap an input in a `form` tag when we are creating UI. [This is what the W3C says about form elements](https://www.w3.org/TR/REC-html40/interact/forms.html):
```
The elements used to create controls generally appear inside a FORM element, 
but may also appear outside of a FORM element declaration when they are used to build user interfaces. 
This is discussed in the section on intrinsic events. 
Note that controls outside a form cannot be successful controls.
```

> do we need to provide an option for components to appear without labels, like Checkbox for example? If label would be optional, we should enforce aria-label in that case?

In the designs, only the text input is without label and I think it makes sense because a checkbox or radio without label would be hard for users to understand.
The only case that I see, right now, where we need a "labeless" Checkbox is this one :

![Screenshot 2021-08-06 at 11 03 31](https://user-images.githubusercontent.com/6597467/128486116-4f926e69-9995-4081-90bd-e787abb8064b.png)

That first column of the table has a Checkbox without a label, but I wonder if extending the table component somehow would be better than exporting a Checkbox without label to the user 🤔 
[This is what Ant UI does apparently](https://ant.design/components/table/)

> in order to provide great experience building forms and using our API we need to provide documentation for components, but also guidelines regarding how to build forms and our design recommendations. @domarku @fabe @damann your insights here would be a great help.

☝️  +100
