### ISSUE TITLE
🐛 Bug - Autocomplete component samples is not working in forma36 website and storybook

### ISSUE THREAD

**Issue by lincetto** [contentful/forma-36#1203]
# Forma 36 bug report

## Summary

- Live sample in https://f36.contentful.com/components/autocomplete/ is not working (items are not filtered when typing in the search box)
- Code sample in https://f36.contentful.com/components/autocomplete/ is not complete and so does not compile (some properties are missing)
- Live sample in https://f36-storybook.contentful.com/?path=/docs/components-autocomplete--basic/ is not working (selecting the item close the suggestions and the selected item is not copied to the text input)
- Code sample in https://f36-storybook.contentful.com/?path=/docs/components-autocomplete--basic/ is not complete and so does not compile

**Comment by Lelith** [comment]
@lincetto Thank you for reporting this issue.

There are two problems: 
1. The example in the README.mdx fails because it is missing `onQueryChange` and `onChange` callback functions.
2. The Autocomplete component is not propagating the information of the currently selected Item to the text-input, so it looks like nothing happened after clicking on one of the filtered items.

As a workaround, until the second issue is fixed, you could propagate the selected Item from the `onChange` callback function directly to the place you need it.

**Comment by Lelith** [comment]
Should be fixed now in https://github.com/contentful/forma-36/releases/tag/%40contentful%2Fforma-36-react-components%403.96.2

**Comment by lincetto** [comment]
:tada:

Thank you!
