### ISSUE TITLE
🐛 Bug - TextInput in TextInput.Group is positioned on top of tooltips

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#1857]
# Forma 36 bug report

## Summary

If I add a `TextInput` and a `CopyButton` with a tooltip in a `TextInput.Group`, the input is positioned on top of the tooltip:

<img width="351" alt="Screenshot 2022-02-07 at 13 03 34" src="https://user-images.githubusercontent.com/219017/152784933-6ce184b5-07c5-4785-a1e5-0ee3e40b352c.png">

The only way to get around it is to set `usePortal` on the `Tooltip`, but there are situations where this is not great, such as when the tooltip is placed so close to the edge of the bounding box that using a portal would create overflow.

**Comment by denkristoffer** [comment]
Only other thing I can think of is that the input is disabled 🤔 

```tsx
<TextInput.Group>
  <TextInput
    isDisabled
    value={contentTypeId}
  />
  <CopyButton value={contentTypeId} />
</TextInput.Group>
```

**Comment by denkristoffer** [comment]
@contentful/team-bauhaus Can anyone have a look again please? 🙇

**Comment by massao** [comment]
Hey @denkristoffer the cause of this one is because when the input is `disabled`, `invalid` or `focused` it has a higher z-index than the other elements, so the glow of the focus or incorrect is always upfront.
So this causes other problems, as if the user has the input selected, and hover on the button, the tooltip will also be behind it, and if we increase the z-index of the tooltip, the glow will be cut, here for example:
![image](https://user-images.githubusercontent.com/1071799/157060488-2a16a01e-48ff-4d31-a709-395cea5aff96.png)
![image](https://user-images.githubusercontent.com/1071799/157060694-ba8c5fc6-c353-44cf-b5fb-e49f4ed597e0.png)

I will create a PR to only have this behaviour of increasing `z-index` only when the field is focused instead, but I think it would be worth for the designers to take a look to see if we can have a different design that wouldn't cause this problem with parts of elements being overlapped, maybe not having the glow, or always having a spacing between elements, don't know.
cc @fabe @domarku

**Comment by denkristoffer** [comment]
Looks like we've lost the error border in groups with this fix: https://www.chromatic.com/test?appId=5fd1dda724cc620021ace8c5&id=62289dd43214f9003aaff9aa
