### ISSUE TITLE
💡 Proposal - Badge component: Pass Icon component

### ISSUE THREAD

**Issue by stephanLeece** [contentful/forma-36#2125]
# Forma 36 contribution proposal

## The problem

In User Interface, there are some use cased where Badge is being used with an Icon / Image as a child component, however, this breaks the layout:

![image](https://user-images.githubusercontent.com/32452823/178482871-ac379e52-daf1-472b-8b48-e1b6071ea162.png)

I understand it is also used in launch, with some color inconsistencies:

![image](https://user-images.githubusercontent.com/32452823/178482962-0188d322-4d2a-4cb3-85bb-a23d14fd82f9.png)

Currently, i'm having to add additional css to fix this, e/g give the Icon absolute positioning.
## The proposed solution

Add an `icon` prop to the Badge, similar to how `IconButton` works.

## Breaking changes

I don't believe so.

**Comment by fabe** [comment]
Thanks for the proposal! We should create some consistency here.

I'd suggest we add `startIcon` and `endIcon` props similar to how icons work in the Button component. We'll write some guidelines on when to use start vs. end, happy to take that on. Let's also make sure we align the icon color with the label color:

<img width="190" alt="image" src="https://user-images.githubusercontent.com/5220692/186692863-217bf19c-f9af-4f12-a4a3-637970ebc341.png">

**Comment by mshaaban0** [comment]
Hi @stephanLeece will you be able to contribute the proposed solution?

**Comment by Wake1st** [comment]
Would it be alright if I took a crack at it?

I've been looking to contribute to some open source, and I think this fits right in the valley of do-able-with-a-challenge for me (at least I hope so 😄).

**Comment by denkristoffer** [comment]
Hey @Wake1st, yes absolutely, that would be great 🙌  Let us know if you need any support, we're happy to help!

**Comment by Wake1st** [comment]
Well, I've got something working, but it's a bit hacky. 

For the most part, I copied from the Button component (no need to reinvent the wheel). The one thing I did add was some padding adjustment for the icons - the sizing is a close call:
`
const getBadgeIconStyle = ({ hasChildren, variant, size }) => {
  ...

  const padding = size === 'small' ? { 
    position: 'relative',
    top: -3,
    padding: `0 ${tokens.spacing2Xs}`,
  } : {
    padding: `1px ${tokens.spacing2Xs}`,
  }

  ...
}`

Since Icons come in bigger sizes, I had to limit them to small and tiny for the default and small badges, respectively. I adjusted the padded for the small icon, since that icon is 18px and the badge is 20px - those fit pretty well.

The small badge, however, is only 16px, which is the same height allotted for the tiny icons. So, some of them look ok:
![image](https://user-images.githubusercontent.com/36935801/189275791-a4cd5495-0a7c-482d-9612-0b9ec396d058.png)

... others look a bit... [oof](https://www.youtube.com/watch?v=3w-2gUSus34):
![image](https://user-images.githubusercontent.com/36935801/189276072-20621102-6208-423d-8d7f-b29d02168c3d.png)


I know its a bit hackey, but it's my first go. If you're fine with this, I'll make a PR; if there are corrections to be made, let me know.

Also, I think the colors look ok, but I am color blind - please let me know if they are off.

**Comment by denkristoffer** [comment]
Thank you @Wake1st! I think it would be easier, at least for me personally, to base discussion around a PR so feel free to put that up 🙂 We can keep it as a draft for now, if you prefer.

**Comment by Wake1st** [comment]
Hey, I'm not able to push my branch. Is there a process to receive authorization? Or a different way of pushing changes?
![image](https://user-images.githubusercontent.com/36935801/189496723-130e92cc-9dbd-4fa9-86b2-2ef3bdafc3fa.png)

**Comment by denkristoffer** [comment]
@Wake1st I replied on Slack 🙂
