### ISSUE TITLE
🐛 Bug - onTabChange fires twice

### ISSUE THREAD

**Issue by jfctfl** [contentful/forma-36#2390]
# Forma 36 bug report

## Summary

When using the Tabs component and registering `onTabChange` without updating the tabs state, the callback is firing twice.

```
const [selectedTab, setSelectedTab] = useState("1");
// not setting the state here on purpose, just want to be notified when callback 
const onTabChanged = () => console.log("callback");
return  <Tabs currentTab={selectedTab} onTabChange={onTabChange}>
       <Tabs.List>
               <Tabs.Tab panelId="1">tab 1</Tabs.Tab>
               <Tabs.Tab panelId="2">tab 2</Tabs.Tab>
       </Tabs.List>
</Tabs>

```
## Environment

Any environment

## Steps to reproduce

See example above

## Expected results

I expect the callback not to fire twice when clicking a tab.

## Actual results

The callback fires twice when clicking a tab.

**Comment by massao** [comment]
Hey @jfctfl
We actually use radix-ui under the hood of the Tabs components, and seems like this bug is also present on their implementation, if you open the [code example](https://www.radix-ui.com/docs/primitives/components/tabs) on code sandbox and set the properties as on your example it will also trigger the callback twice.
