### ISSUE TITLE
🐛 Bug - Autocomplete onSelectItem is not executed when an item is selected a second time

### ISSUE THREAD

**Issue by cmatthews-uwhealth** [contentful/forma-36#2641]
# Forma 36 bug report

## Summary

As reported earlier in [this issue report](https://github.com/contentful/forma-36/issues/2622), repeated clicks on an autocomplete item only trigger `onSelectItem` with the first click, and clicks afterwards do not trigger `onSelectItem`.

## Environment
Microsoft Edge and Google Chrome, both when running locally and when used as an embedded field in a Contentful App.

## Steps to reproduce

The behavior described below can be seen here: https://deploy-preview-61--uwhealth-contentful-ui-extensions.netlify.app/content-feed. Select a "Content Types" value to enable the "Filter Fields" Autocomplete component, then follow the steps below.

1. Using an `<Autocomplete>` component with `isGrouped` applied, click on the input box to deploy the dropdown menu of autocomplete items.
2. Click one of the options, the `onSelectItem` function will execute at this time.
3. Click the same option a second time. The `onSelectItem` function will not execute.
Note that the `onSelectItem` function can be made to execute by clicking a different item and then clicking the original item again.

## Expected results

The `onSelectItem` function should execute every time an item is clicked, even on repeat clicks.

## Actual results

The `onSelectItem` function executes once when an item is clicked, but will not execute again no matter how many times the item is clicked. This bug is "reset" by clicking a different item.

**Comment by Lelith** [comment]
Hey, thank you for reporting the issue. But could you provide a minimal example of your implementation? Because if you use a React State to handle your current selection? I tried to reproduce the issue here in our [playground](https://f36.contentful.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwAQCUYBDMPAM0whVwHJNjSaBuAHQDtUMddhcBBAK7YIkdABsY2GABpcAZWwkA1rIAKRTEQDmmtAAtcAX1wUqtAAKQ2U62QFiA9GQDMANgC0ojGxjWAzszs7DAAHlx4sGRE9uQCbKRIEGz8QiJUaBJSALIxSHIwEglJAKIhROIwABQAlDzsuLhWfnh+aCQwfrgAvLgA2vUNPLhs5TDwtAAqmgBuBbgAQmIQWjSy2ACeaGO0AMJUKHFIGzRG0gMNvCMo2zQAYkhsI-EwC0sra5s3eygHHMen5yGVxu92wPj8nT4aDQq1wGy24xoWRgUCQAhQJ0MZ2Sg0uo0RADkYAB3ToAdRgACM-EcYLD4Tdkaj0ZjsYMgfjaDBvtdMGAXjsiIo3gI6R8EbQADIaLR0gE4i7DTk0VR6CDCXAAcSIYgkmHW9M+iOlmFlrIGAF1WGwBg4HLgJnoXs0hS82BBibhmlgOrgiMkNJp1rgIGQvQUYKQUV62vy-LJ3XgAFYCZp+r3YTAPLQDJp4Xp+CNRqByWMdWSF7D5QpSEtlvwW7oEBjYAB0qZgCldlV6Fuq1oaeb6ZCQYik9CgAEkpCh4+HsPcxzAJ9OYLPGz1CCQ2x2u1JKq12n5+0EcUO9P6oBJJ2w0EIAGo60U7C9sWVNyrTJ8wWpdAB8dQKo0SRpj4xKLuOKKrrOTaHnGrYjkumCVJUtIoL+f6Ag0aGtsCrbCJKHrLoKhY1K2DxgGIAiwH4n7fvhECEcSxFEKR1TVGygwnkBlYQcuUEzrRYF8SugncQ0hjWrmIF4K+V6dkW2DQR+aEYYB7J2nCyxaBI4Y1okbB+ICSBkAeikoqWR7kfEVE0ahM64aM7HAFh87VpGtaWXGKFoPQ0x7j+3QAb5MD+YoUgIaO44oQUalzAAhF0PQ4cC7GAsYBSFup7JueZdZHj5fkBWpvStmVIVha6sgpaMfYDoMhgDAMkmng09DYAImDJJUgIADxdmASgmBIIQACJIPQRRsF0LDgBAVEoDaIB+mISBaGw0F+DNIAujgs2YUBDS9YIwheJkMCudhgldMAiGQVOgmNYdgxJDed7YI+VHcq+so3XJ163g+34vv6spPTlL1sO5pDQX9l4SNDSkzuDEO4GhEwQAoWZvjd9lrmpNXXCjEP0GwsCYLDwB4+hQVow5wLEzlmlkk6yQAAZSCE2AAPJsHwZDjojbNo50bOzZRxCYLNbPVXgxKjmIjQSP6cJOg6oRKYDeBEALy5+skEBoNgBki3pHkopdcIa7z-OC4p20Sxos2W5RECFrby6IzdURiIWjMNA4B2ub1h5sAdqO4L16iaDoRD6H+iPRnBHTwL1DjR9ouh6OHqO9fYOcR8AhY1hZ9atigccocn1Vk6Eak9c9EO9atuBKDA6w3Q8sAhIYf5F2Whhp6tBeo+x-uDGn+fBw4ocj2nA1KDn3FPSAhhAA) but for me it toggles the selection.

In worst case you can reset the internal-form selectedItem of the Autocomplete by reset the `selectedItem` property 
```
<Autocomplete {...args} selectedItem={mySelectedState} onSelectItem= {(item) => { 
  // do something with your selection
  setMySelectedState('');
 }
}
```

**Comment by JonNorman** [comment]
Just to comment that I am also running into this issue, it's a bit hard to work out exactly what is going on, but I am seeing that subsequent clicks on the same item do not trigger a subsequent call to the `onSelectItem`/`renderItem`.

https://github.com/user-attachments/assets/04c7c889-9a0b-4729-b7cb-f1f03e5b32eb

```jsx
import { Autocomplete, Stack } from '@contentful/f36-components';
import { SearchIcon } from '@contentful/f36-icons';
import { getStringMatch } from '@contentful/f36-utils';

import { useState } from 'react';

export const DropDownGroupedMinimal = () => {
  const groupedItems = [
    {
      groupTitle: 'Group 1',
      options: [
        {
          name: '1A',
        },
        {
          name: '1B',
        },
        {
          name: '1C',
        },
      ],
    },
    {
      groupTitle: 'Group 2',
      options: [
        {
          name: '2A',
        },
        {
          name: '2B',
        },
        {
          name: '2C',
        },
      ],
    },
  ];
  const [filteredItems, setFilteredItems] = useState(groupedItems);
  const [selectedItems, setSelectedItems] = useState<{ name: string }[]>([]);

  const handleInputValueChange = (value: string) => {
    const newFilteredItems = groupedItems.map((group) => ({
      groupTitle: group.groupTitle,
      options: group.options.filter((option) => option.name.toLowerCase().includes(value.toLowerCase())),
    }));

    setFilteredItems(newFilteredItems);
  };

  const handleSelectItem = (item: { name: string }) => {
    console.log(`Clicked on ${item.name} with [${selectedItems.map((item) => item.name).join(',')}]`);
    setSelectedItems((prevItems) => {
      if (prevItems.some((i) => item === item)) {
        console.log(`Removing ${item.name}`);
        return prevItems.filter((prevItem) => prevItem.name !== item.name);
      } else {
        console.log(`Adding ${item.name}`);
        return [...prevItems, item];
      }
    });
  };

  return (
    <Stack flexDirection="column" alignItems="start">
      <Autocomplete
        isGrouped={true}
        items={filteredItems}
        onInputValueChange={handleInputValueChange}
        onSelectItem={handleSelectItem}
        itemToString={(item) => item.name}
        textOnAfterSelect="clear"
        closeAfterSelect={false}
        icon={<SearchIcon variant="muted" />}
        renderItem={(item, inputValue) => {
          const { before, match, after } = getStringMatch(item.name, inputValue);
          return (
            <>
              {before}
              <b>{match}</b>
              {after}
              {selectedItems.some((i) => i.name === item.name) ? ' (selected)' : ''}
            </>
          );
        }}
      />
    </Stack>
  );
};

```

**Comment by JonNorman** [comment]
Actually, I think we can close this – see edit above!
