### ISSUE TITLE
Contribution Proposal: Box Component

### ISSUE THREAD

**Issue by wichniowski** [contentful/forma-36#318]
Hey F36 Community 👋

I'm proposing a new component that will reduce the overhead of writing CSS for spacing purposes. I many times see the same code being written to add margins and paddings, and I think we'd benefit from a Box component that will add a spaced box around its children. This component would simply expose padding and margin CSS properties to be set with our tokens. 

**Box PropTypes**

Property | Values | Default |  
------------ | ------------- | -------------
element | any html element | div
padding |  F36 spacing token | undefined
paddingTop |  F36 spacing token | undefined
paddingRight |  F36 spacing token | undefined
paddingBottom |  F36 spacing token | undefined
paddingLeft |  F36 spacing token | undefined
margin |  F36 spacing token | undefined
marginTop |  F36 spacing token | undefined
marginRight |  F36 spacing token | undefined
marginBottom |  F36 spacing token | undefined
marginLeft |  F36 spacing token | undefined
marginHorizontal | F36 spacing token | undefined
marginVertical | F36 spacing token | undefined
paddingHorizontal | F36 spacing token | undefined
paddingVertical | F36 spacing token | undefined
```
<Box paddingTop="xs" margin="l" element="span">
  {children}
</Box>
```

Let me know what you think 😊

**Comment by m10l** [comment]
Nice, sounds like a good idea. I think the addition of `marginHorizontal`, `marginVertical`, `paddingHorizontal`, and `paddingVertical` would be handy too

**Comment by wichniowski** [comment]
@m10l that sounds good will update the proposal!

**Comment by suevalov** [comment]
I love it 👍 

Probably also makes sense to create `Flex` component which would reuse `Box` and extend it with flexbox specific properties.

**Comment by suevalov** [comment]
Actually, I think all values should be undefined by default, not `m`

**Comment by joaoramos** [comment]
This feels right 👏 @suevalov what would be the benefit of using undefined for all values?

**Comment by suevalov** [comment]
@joaoramos 
1. If all of them are `m` then they conflict with each other. 
2. If you take a look at our emotion styles then you would notice that people are using one or two paddings/margins in 90% cases. Imagine that I need a Box with paddingRight=l.

If all default are nullable
```
<Box paddingRight="l" />
```

If they are `m` like described above:

```
<Box padding="none" margin="none" paddingRight="l" />
```

So we'll end up with padding="none" and margin="none" in 90% cases.

**Comment by wichniowski** [comment]
@suevalov you're totally right I'll update the proposal!

**Comment by wichniowski** [comment]
@suevalov @m10l @joaoramos if there are no other comments or ideas then the once I addressed I'd move on and open a PR for this component.

**Comment by mshaaban0** [comment]
The approach looks pretty awesome, I would like to raise the awareness for the cost of such components vs using tokens as classnames...

Each react _functional_ component we introduce has an average cost of **4ms** (mount time), that's on (Chrome/Macbook i5/16GB 2018) model, hence the cost will increases on less performant devices like old android phones.

In my opinion, such component will be spread like a wildfire across the library :) another approach to ensure devs use the correct spacing values, is to use [Stylelint](https://github.com/stylelint/stylelint) and enforce specific values/variables for margins and paddings.

e.g.
```scss
.foo {
  /* style linter pass */
  margin: var(--f36-spacing-xs);
}

.foo {
  /* style linter fail */
  margin: 13px;
}
```
Thoughts are welcome 😊

**Comment by wichniowski** [comment]
Hey @mshaaban0 

thanks for bringing this up! This is a pretty good concern also that we actually don't have a consistency problem. So tokens are widely used, this component would mostly cater to convenience. Since we're using a CSS in JS solution and component scoped CSS I see the same code being written many times for just achieving some basic spacing. This component should be a convenient solution to apply this spacing and to stay consistent in our spacing scale. So the question is do we want to do this tradeoff of performance for a better developer experience?

So maybe we should provide more utilities like FCSS to use with specific CSS in JS solutions.
I'll also look into alternatives :)

**Comment by mshaaban0** [comment]
Thanks for the explanation, sorry I thought the problem is with consistency.

> So the question is do we want this tradeoff of performance for a better developer experience?

Yes, I don't really have a strong opinion against it, just thinking out loud.

**Comment by davidfateh** [comment]
Without strict enforcement, the Box component will likely be optionally used by most devs. In this case, we will have CSS tokens AND Box components throughout code bases, which to me only makes things more convoluted.

> So the question is do we want this tradeoff of performance for a better developer experience?

What are the real metrics to track here that will show a better dev experience will outweigh performance? 

In my opinion, using the CSS properties for `margin` and `padding` are already a great dev experience and provide the most performance possible.

Not to mention other things like
A) reduced markup within JSX without Box
B) reduce DOM elements without Box
 C) Not using Box stays closer to patterns which most devs are already familiar with (HTML for layout, CSS for styling)

My 2¢.

**Comment by mshaaban0** [comment]
Would exposing a sass mixin help? e.g.
```scss
.foo {
  @include box-spacing(
   $paddingRight: 'm',
   $paddingLeft: 'l',
   $margin: 'none'
  );
}
```

**Comment by jo-sm** [comment]
I have a few thoughts on the issue. Bear with me! 😄 

I'm curious, what is this specifically trying to solve -- is this trying to solve spacing (margins, padding) to wrappers like a `div` and essentially replace those wrapper with our own component? Or are we trying to avoid people adding wrappers simply for spacing purposes?

If we are trying to avoid the latter, I believe the real solution to this problem is to have default spacing on all components, such that you only have to add spacing between components if there is something that needs to be different than the default. This problem only really presents itself because there isn't spacing by default on anything; for example, if you take a component such as `Card`, you probably would only need to add spacing classes but likely little else as provides internal styles already. 

Barring default spacing being an option, I think that if we are trying to avoid/help people who add spacing to our components, then I don't believe that the Box component is the best approach. I think that a better solution would be to add an attribute to every, or almost every, component that allows you to customize spacing. I think performance is a potential problem, but I'd worry more about the cognitive overhead of having even more components.

However, if we are trying to avoid the former, for users to avoid using layout wrapper divs, then I think a Box component may have a large benefit, even taking into account the potential cognitive overhead and performance issues.

One red flag that keeps coming to my mind with adding the Box component is now you are going to be explicitly blessing and mixing template with logic (JSX) with layout and styles. I would guess people don't often mix those (and those that do, most likely use CSS-in-JS, which this isn't exactly compatible with as far as I can tell) and somehow use styles in a different way (import a `.css` file, `emotion`, etc.) and so mixing spacing into the template while the other styles live somewhere else may bring complications to those using Forma. This adds to the cognitive overhead issue I mentioned earlier, but now not only is it due to our components (which can most likely be solved with familiarity and documentation) but also due to styling living in both templates and in the stylesheets. 

Overall I'm not entirely convinced a `Box` component is a good solution, default spacing argument aside, because it will make things more complicated for those that use our library.

**Comment by wichniowski** [comment]
The idea is inspired by other design systems that expose box components as a shorthand for wrappers, mostly divs. This component should provide a shorthand to create a spaced box (and maybe other attributes like background colors). But I totally understand those concerns brought up by @davidfateh and @jo-sm that this will mix paradigms and make things confusing. So right now it introduces more complexity and does not seem to be a good solution so I suggest to close this proposal and work on better documentation on usage of our spacing tokens. Thank you for your feedback!
