### ISSUE TITLE
Missing `selected` type for AssetCard and EntryCard components

### ISSUE THREAD

**Issue by suevalov** [contentful/forma-36#460]
We need to add `selected?: boolean` for those components.

In general, it would be nice to extend CardProps to avoid duplication / or missing type problems between AssetCard / EntryCard / Card components.

**Comment by jacquesporveau** [comment]
I'm going to start working on this now.

**Comment by jacquesporveau** [comment]
I've done some work on this. It's pretty tricky to build a clean type that can be infer from the Card component. I think the issue is that all the props required for the Card component are not actually required for it's abstracted AssetCard component.

I ended up trying a intersection of types.

You get into this place kind of like this:

```tsx
type GreeterProps = {
  firstName: string;
  lastName: string;
}

const Greeter: React.FC<GreeterProps> = ({ firstName, lastName }) => {
 return <h1>Hello, {`${firstName} ${lastName}`}</h1>;
};

type FancyGreeterProps = {
  lastName: string;
} & GreeterProps;

const FancyGreeter: React.FC<FancyGreeterProps> = ({ lastName }) => {
 return <h1>Hello, {`Han ${lastName}`}</h1>;
};
```
Where calling `<FancyGreeter lastName='Solo' />` results in errors thrown because the GreeterProps expect there to be a `firstName` prop sent down.

I think you would need to do something like picking which ones of the props the abstracted `AssetCardComponent` would use from the `CardComponentProps` in which case the idea of trying to base them off each other doesn't really offer much value.

Anyway would love any advice you have on this. I think tomorrow I might look a bit into trying to exclude or include certain fields from other types for a bit. Let me know if I am off the mark here.

Here is my branch:

https://github.com/jacquesporveau/forma-36/tree/jacquesporveau/unify-prop-types

@suevalov

**Comment by burakukula** [comment]
Hey @jacquesporveau! 👋 So sorry for the delay with the follow up. From my perspective this is the right approach, I would probably go the same way. I guess we would be able to extract shared types in the `Card` component and imported it into others, in the pattern that you proposed. @suevalov what do you think? Maybe you would have some other advice here?

**Comment by suevalov** [comment]
I think the proposed solution is good

**Comment by burakukula** [comment]
@suevalov thx for feedback! 🙂
@jacquesporveau would you like to continue into the PR with this topic? Let us know if you need any support! Thx a lot for you contributions 👏

**Comment by jacquesporveau** [comment]
I'll continue thanks guys

**Comment by jacquesporveau** [comment]
I am not going to be pursuing this work.
