### ISSUE TITLE
🐛 Bug - Dropdown and Tooltip don't work well together

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#614]
# Forma 36 bug report

## Summary

Forma's tooltip and dropdown don't play well together. It's not easy to use a tooltip on a dropdown's toggle element and ensure that the tooltip is hidden when the dropdown opens.

## Steps to reproduce

https://codesandbox.io/s/fervent-sky-h2h8x?file=/src/App.js

Click the button.

## Expected results

The dropdown should open and the tooltip should hide.

## Actual results

The tooltip stays visible and the dropdown doesn't open.

If you uncomment line 11-13 in the Codesandbox, the dropdown opens as it should, but then the tooltip doesn't hide. This is not strictly a bug, but it's a use case we should handle somehow.

**Comment by mshaaban0** [comment]
@gui-santos Please have a look, thanks

**Comment by gui-santos** [comment]
I investigated this the best I could and the only way I could make it work without refactoring the two components all over again was by removing the onClose prop passed to the Dropdown, but if we do that we lose the functionality of clicking outside and closing the dropdown

I worked on the same sandbox @denkristoffer posted. You can all check it out here

https://codesandbox.io/s/flamboyant-hamilton-zkxgq?file=/src/App.js

**Comment by suevalov** [comment]
Fixed in v4. [Here is a working example](https://f36.contentful.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwAQCUYBDMPAM0whVwHJNjSaBuAHQDtUMddhcBZGGwCuAGlwBJSGwBCQ7NghsxAFQgQANtiRpcAX1wUqtAAJTsg7GSHqA9GQDMANgC0kdIosBnZu05Y8vALCkop6BpTUNKaK5myW1nZOzkhS3qxs7DAAHlx4sGRE1uRCbKRIodJEnilBQgAUAJQ87Li49NhCmGy4dS2tuAA8tQB8ff2DtQB0yphIAOZzMJij3eP9A6oaWjpmFgC8LCAAEjDq6hCHK2trAyEycgoZq9fjAG5Es0RxByCeMFJQD4AT0OYxerRSij2wCGgiEd1wNmGujB4I+SCIznURAARqcfgoFuoYLgUHDQc8XkjUesbJtNNorjcbFMZvNFssabDhJMADJITzYJnXblCSbicwoYYAYXoRHMuC+uAsmCBAxZcPFkuFNymEpgUsIKAgrxJSpVao1PP1UpprVFWoNwwAoig8VBlVkBVo2HNlXFVeq9dquVaxfzBTqg3CmQ10ii2CBdEA)
